/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.musicplayer;

import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author 1104691
 */
public class Frame extends javax.swing.JFrame {
    
    SongManager smInstance;
    Song selected;
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        setLocationRelativeTo(null);
        smInstance = new SongManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void drawSongButtons(){
        String[] songNames = smInstance.getWorkspace().stream()
                .map(Song::toString)
                .toArray(String[]::new);
        
        mList.setModel(new DefaultComboBoxModel<>(songNames));
    }
    
    private void drawSongButtons(String search){
        String[] songNames = smInstance.getWorkspace().stream()
                .map(Song::toString)
                .filter(s->s.contains(search))
                .toArray(String[]::new);
        
        mList.setModel(new DefaultComboBoxModel<>(songNames));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rFrame = new javax.swing.JPanel();
        rVolume = new javax.swing.JSlider();
        rDuration = new javax.swing.JProgressBar();
        mFrame = new javax.swing.JPanel();
        mSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mList = new javax.swing.JList<>();
        topMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        setFile = new javax.swing.JMenuItem();
        refreshFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        playPause = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        rFrame.setBackground(new java.awt.Color(255, 255, 255));
        rFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rVolume.setMaximum(6);
        rVolume.setMinimum(-80);
        rVolume.setValue(-37);
        rVolume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rVolumeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout rFrameLayout = new javax.swing.GroupLayout(rFrame);
        rFrame.setLayout(rFrameLayout);
        rFrameLayout.setHorizontalGroup(
            rFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rFrameLayout.setVerticalGroup(
            rFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(rFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rDuration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rVolume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mFrame.setBackground(new java.awt.Color(255, 255, 255));
        mFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mSearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                mSearchInputMethodTextChanged(evt);
            }
        });
        mSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSearchActionPerformed(evt);
            }
        });
        mSearch.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mSearchPropertyChange(evt);
            }
        });
        mSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mSearchKeyTyped(evt);
            }
        });

        mList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "set your music directory to get started (Ctrl+O)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        mList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(mList);

        javax.swing.GroupLayout mFrameLayout = new javax.swing.GroupLayout(mFrame);
        mFrame.setLayout(mFrameLayout);
        mFrameLayout.setHorizontalGroup(
            mFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(mSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                .addContainerGap())
        );
        mFrameLayout.setVerticalGroup(
            mFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        setFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        setFile.setText("Set File Path");
        setFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFileActionPerformed(evt);
            }
        });
        jMenu1.add(setFile);

        refreshFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        refreshFile.setText("Refresh");
        jMenu1.add(refreshFile);

        topMenu.add(jMenu1);

        jMenu2.setText("Playback");

        playPause.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, 0));
        playPause.setText("Play/Pause");
        playPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPauseActionPerformed(evt);
            }
        });
        playPause.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                playPauseKeyReleased(evt);
            }
        });
        jMenu2.add(playPause);

        topMenu.add(jMenu2);

        setJMenuBar(topMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mSearchActionPerformed

    private void setFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setFileActionPerformed
        smInstance.setDirectory(jMenu1);
        drawSongButtons();
    }//GEN-LAST:event_setFileActionPerformed

    private void playPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPauseActionPerformed
        System.out.println(selected);
        smInstance.playSong(selected);
    }//GEN-LAST:event_playPauseActionPerformed

    private void rVolumeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rVolumeMouseReleased
        smInstance.setVolume(rVolume.getValue());
    }//GEN-LAST:event_rVolumeMouseReleased

    private void mSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mSearchKeyReleased
        
    }//GEN-LAST:event_mSearchKeyReleased

    private void playPauseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playPauseKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_SPACE) {
            
        }
    }//GEN-LAST:event_playPauseKeyReleased

    private void mListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mListValueChanged
        selected = smInstance.getSongFromName(mList.getSelectedValue());
    }//GEN-LAST:event_mListValueChanged

    private void mSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mSearchKeyTyped
        drawSongButtons(mSearch.getText());
    }//GEN-LAST:event_mSearchKeyTyped

    private void mSearchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mSearchPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_mSearchPropertyChange

    private void mSearchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_mSearchInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mSearchInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mFrame;
    private javax.swing.JList<String> mList;
    private javax.swing.JTextField mSearch;
    private javax.swing.JMenuItem playPause;
    private javax.swing.JProgressBar rDuration;
    private javax.swing.JPanel rFrame;
    private javax.swing.JSlider rVolume;
    private javax.swing.JMenuItem refreshFile;
    private javax.swing.JMenuItem setFile;
    private javax.swing.JMenuBar topMenu;
    // End of variables declaration//GEN-END:variables
}
